import { type NextPage } from "next";
import { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
// import Metronome from "../components/Metronome";
import dynamic from "next/dynamic";

const Home: NextPage = () => {
  const Metronome = dynamic(() => import("../components/Metronome"), {
    ssr: false,
  });
  return (
    <>
      <Head>
        <title>Groovy Metronome</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center overflow-x-hidden bg-[#CBD5E1]">
        <Metronome />
      </main>
    </>
  );
};

export default Home;
