import { type NextPage } from "next";
import Head from "next/head";
// import Metronome from "../components/Metronome";
import dynamic from "next/dynamic";
// import Waveform from "../components/Waveform";

const Home: NextPage = () => {
  // const Metronome = dynamic(() => import("../components/Metronome"), {
  //   ssr: false,
  // });
  // const Waveform = dynamic(() => import("../components/Waveform"), {
  //   ssr: false,
  // });
  const Example = dynamic(() => import("../components/Example"), {
    ssr: false,
  });
  return (
    <>
      <Head>
        <title>Groovy Metronome</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="z-20 flex min-h-screen flex-col items-center justify-center overflow-x-hidden bg-[#CBD5E1]">
        {/* <Metronome /> */}
        <Example />
      </main>
    </>
  );
};

export default Home;
